#%RAML 1.0 Library
types:
  TokenReq:
    description: |-
      This api is used to get anypoint login token
    type: object
    properties:
      username:
        required: true
        type: string | nil
        description: "username"
        example: "xxxx"
      password:
        required: true
        type: string | nil
        description: "password"
        example: "xxxx"
          